### ISSUE TITLE
Improve footer component

### ISSUE THREAD

**Issue by JeanBarriere** [storyscript/components#20]
Improve the footer component to match design:
![image](https://user-images.githubusercontent.com/11390722/63153360-677f9380-c00e-11e9-992a-33fd8473de28.png)

**figma: https://www.figma.com/file/YEK0PcLu4zkB3DgPtEnD2F/Storyscript-io?node-id=0%3A1**

**Comment by Arinono** [comment]
Did it here : https://github.com/storyscript/components/pull/25
